/*°′″  «»  ≤≥  ≠≈  —¦  ÷×  !¡  ©®  £€  $¢  №⋕  λμ  πφ  ∑∏  ¶§  †‡  ±∞  √∆  ∫∳ */
#error "Joining_Group isn't implemented"

/*  extracted/DerivedJoiningGroup.h
*/
#define No_Joining_Group_JG // No_Joining_Group
#define Ain_JG // Ain
#define Alaph_JG // Alaph
#define Alef_JG // Alef
#define Beh_JG // Beh
#define Beth_JG // Beth
#define Dal_JG // Dal
#define Dalath_Rish_JG // Dalath_Rish
#define E_JG // E
#define Feh_JG // Feh

#define African_Feh_JG // African_Feh
#define African_Noon_JG // African_Noon
#define African_Qaf_JG // African_Qaf
#define Burushaski_Yeh_Barree_JG // Burushaski_Yeh_Barree
#define Farsi_Yeh_JG // Farsi_Yeh
#define Fe_JG // Fe
#define Final_Semkath_JG // Final_Semkath
#define Gaf_JG // Gaf
#define Gamal_JG // Gamal
#define Hah_JG // Hah
#define Hanifi_Rohingya_Kinna_Ya_JG // Hanifi_Rohingya_Kinna_Ya
#define Hanifi_Rohingya_Pa_JG // Hanifi_Rohingya_Pa
#define He_JG // He
#define Heh_JG // Heh
#define Heh_Goal_JG // Heh_Goal
#define Heth_JG // Heth
#define Kaf_JG // Kaf
#define Kaph_JG // Kaph
#define Khaph_JG // Khaph
#define Knotted_Heh_JG // Knotted_Heh
#define Lam_JG // Lam
#define Lamadh_JG // Lamadh
#define Malayalam_Bha_JG // Malayalam_Bha
#define Malayalam_Ja_JG // Malayalam_Ja
#define Malayalam_Lla_JG // Malayalam_Lla
#define Malayalam_Llla_JG // Malayalam_Llla
#define Malayalam_Nga_JG // Malayalam_Nga
#define Malayalam_Nna_JG // Malayalam_Nna
#define Malayalam_Nnna_JG // Malayalam_Nnna
#define Malayalam_Nya_JG // Malayalam_Nya
#define Malayalam_Ra_JG // Malayalam_Ra
#define Malayalam_Ssa_JG // Malayalam_Ssa
#define Malayalam_Tta_JG // Malayalam_Tta
#define Manichaean_Aleph_JG // Manichaean_Aleph
#define Manichaean_Ayin_JG // Manichaean_Ayin
#define Manichaean_Beth_JG // Manichaean_Beth
#define Manichaean_Daleth_JG // Manichaean_Daleth
#define Manichaean_Dhamedh_JG // Manichaean_Dhamedh
#define Manichaean_Five_JG // Manichaean_Five
#define Manichaean_Gimel_JG // Manichaean_Gimel
#define Manichaean_Heth_JG // Manichaean_Heth
#define Manichaean_Hundred_JG // Manichaean_Hundred
#define Manichaean_Kaph_JG // Manichaean_Kaph
#define Manichaean_Lamedh_JG // Manichaean_Lamedh
#define Manichaean_Mem_JG // Manichaean_Mem
#define Manichaean_Nun_JG // Manichaean_Nun
#define Manichaean_One_JG // Manichaean_One
#define Manichaean_Pe_JG // Manichaean_Pe
#define Manichaean_Qoph_JG // Manichaean_Qoph
#define Manichaean_Resh_JG // Manichaean_Resh
#define Manichaean_Sadhe_JG // Manichaean_Sadhe
#define Manichaean_Samekh_JG // Manichaean_Samekh
#define Manichaean_Taw_JG // Manichaean_Taw
#define Manichaean_Ten_JG // Manichaean_Ten
#define Manichaean_Teth_JG // Manichaean_Teth
#define Manichaean_Thamedh_JG // Manichaean_Thamedh
#define Manichaean_Twenty_JG // Manichaean_Twenty
#define Manichaean_Waw_JG // Manichaean_Waw
#define Manichaean_Yodh_JG // Manichaean_Yodh
#define Manichaean_Zayin_JG // Manichaean_Zayin
#define Meem_JG // Meem
#define Mim_JG // Mim

#define Noon_JG // Noon
#define Nun_JG // Nun
#define Nya_JG // Nya
#define Pe_JG // Pe
#define Qaf_JG // Qaf
#define Qaph_JG // Qaph
#define Reh_JG // Reh
#define Reversed_Pe_JG // Reversed_Pe
#define Rohingya_Yeh_JG // Rohingya_Yeh
#define Sad_JG // Sad
#define Sadhe_JG // Sadhe
#define Seen_JG // Seen
#define Semkath_JG // Semkath
#define Shin_JG // Shin
#define Straight_Waw_JG // Straight_Waw
#define Swash_Kaf_JG // Swash_Kaf
#define Syriac_Waw_JG // Syriac_Waw
#define Tah_JG // Tah
#define Taw_JG // Taw
#define Teh_Marbuta_JG // Teh_Marbuta
#define Teh_Marbuta_Goal_JG // Teh_Marbuta_Goal
#define Teth_JG // Teth
#define Thin_Yeh_JG // Thin_Yeh
#define Vertical_Tail_JG // Vertical_Tail
#define Waw_JG // Waw
#define Yeh_JG // Yeh
#define Yeh_Barree_JG // Yeh_Barree
#define Yeh_With_Tail_JG // Yeh_With_Tail
#define Yudh_JG // Yudh
#define Yudh_He_JG // Yudh_He
#define Zain_JG // Zain
#define Zhain_JG // Zhain
